version: "3"
services:
  web:
    build: .
    container_name: "CryptoCrawler.java"
    links:
    - mongodb
    depends_on: 
    - mongodb
    ports:
      - "8000:8000"
  mongodb:
    image: mongo:latest
    ports:
            - "27017:27017"
    command: mongod